name: get job id run test
on: 
  push: 
    branches: [master, dev]
env: 
  JOB_NAME: xxx 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-id:
    runs-on: ubuntu-latest
    name: xxx

    steps:
      - uses: 'ayachensiyuan/get-action-job-id@dev'
        id: setId
        with: 
          job-name: ${{ env.JOB_NAME }}
      
      # get id     
      - name: get-id1
        run: echo "The current job id is ${{ steps.setId.outputs.jobId }}"
